server:
  port: 8082
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        accounts-in:
          destination: accounts
          contentType: application/json